Split headers
AVassilev98/Pacem pull request #2
Opened 2023-05-16 07:58 UTC by zeneiny

Put headers into a separate directory to avoid clutter

2023-05-19 04:53 UTC, AVassilev98 requested changes

2023-05-19 04:53 UTC, AVassilev98 commented on src/common.h
> +            std::stringstream ss{};                                                                                                                            \
Thanks!

2023-05-19 04:53 UTC, AVassilev98 commented on src/main.cpp
> +        while (glfwGetTime() - lastTime < delay){}
I don't wanna really pull this implementation, since it will cause work for me in the near future. You can implement it any way you like which won't cause the issues I mentioned in [our previous discussion](https://github.com/AVassilev98/Pacem/pull/1#discussion_r1194569094)

You can also just take out this commit from the review. Either is fine by me

2023-05-19 04:53 UTC, AVassilev98 commented on src/main.cpp
> +        while (glfwGetTime() - lastTime < delay)
See: https://github.com/AVassilev98/Pacem/pull/1#discussion_r1194569094

2023-05-19 04:53 UTC, AVassilev98 commented on CMakeLists.txt
> +target_include_directories(Pacem AFTER PUBLIC include)
Sure, I'm fine with this

2023-05-20 12:07 UTC, zeneiny commented
@AVassilev98 Yeah I got rid of my jank busywaiting vsync lol
We can do it properly later, I was just tired of my laptop fans spinning up everytime I ran Pacem since it'd use 100% GPU instantly

2023-05-21 20:50 UTC, AVassilev98 approved these changes

2023-05-22 07:29 UTC, zeneiny commented
@AVassilev98 Merge this shit before you make another 2.5k line change please

2023-05-22 11:52 UTC, AVassilev98 commented
> @AVassilev98 Merge this shit before you make another 2.5k line change please

Sorry, I'm sorry.

sorry

2023-05-22 11:52 UTC, merged